version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: always
    networks:
      - common_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./var/log/nginx:/var/log/nginx
      #- ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
    depends_on:
      - backend
    ports:
      - 1337:80
    networks:
      - common_network


volumes:
  static_volume:
networks:
  common_network:
    driver: bridge