FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir /app/static

COPY ./backend .

RUN apt-get update
RUN apt-get install -y gcc
RUN pip install -r requirements.txt