version: '3'

services:

  backend:
    build: 
      dockerfile: Dockerfile.backend
      context: .
    ports:
      - 8888:8000
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/static
    command: >
      sh -c "python3 backend/manage.py runserver 0.0.0.0:8000"
    restart: always
  
  # frontend:
  #   build:
  #     dockerfile: Dockerfile.frontend
  #     context: .
  #   container_name: frontend_react
  #   volumes:
  #     - ./frontend:/app/frontend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.Server
    container_name: nginx
    image: nginx
    volumes:
      - static_volume:/app/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx:/var/log/nginx
      #- ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
    depends_on:
      - backend
    expose:
      - 80
    ports:
      - 81:80


volumes:
  static_volume: