version: '3'

volumes:
  static_volume:
  media:

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file: .env
    network_mode: "host"
    restart: always
    volumes:
      - static_volume:/backend_static
      - media:/app/media

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    command: cp -r /app/build/. /frontend_static/
    network_mode: "host"
    volumes:
      - static_volume:/frontend_static

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    restart: always
    network_mode: "host"
  