# Generated by Django 4.2 on 2023-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('PAO', models.BooleanField(default=True, verbose_name='ПАО')),
                ('DZO', models.BooleanField(default=True, verbose_name='ДЗО')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.CharField(max_length=100, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('subscription', models.BooleanField(default=False, verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'подписку',
                'verbose_name_plural': 'подписки на новости',
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(choices=[('Прибыли и убытки РТК', 'Прибыли и убытки РТК'), ('РТК + Tele2', 'РТК + Tele2'), ('Сегментная отчетность', 'Сегментная отчетность')], max_length=100, verbose_name='Отчет')),
                ('email', models.CharField(max_length=100, verbose_name='Email пользователя')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('subscription', models.BooleanField(default=False, verbose_name='Подписка')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_via_portal', models.BooleanField(default=True, verbose_name='Добавлено через портал')),
                ('moderator_is_decision', models.BooleanField(default=False, verbose_name='Проверка модератора')),
                ('moderator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модератор')),
                ('data_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('comment_delete', models.TextField(blank=True, null=True, verbose_name='Комментарий при удалении')),
            ],
            options={
                'verbose_name': 'отчетность',
                'verbose_name_plural': 'отчетности',
                'ordering': ['-data'],
            },
        ),
    ]
