# Generated by Django 4.2 on 2023-05-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reporting',
            old_name='email',
            new_name='user',
        ),
    ]
