# Generated by Django 4.2 on 2023-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_news_options_alter_reporting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporting',
            name='report',
            field=models.CharField(choices=[('Прибыли и убытки РТК', 'Прибыли и убытки РТК'), ('РТК + Tele2', 'РТК + Tele2'), ('Сегментная отчетность', 'Сегментная отчетность')], max_length=100, verbose_name='Отчет'),
        ),
    ]
