# Generated by Django 4.2 on 2023-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_email_news_user_rename_email_reporting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
