# Generated by Django 4.2.1 on 2023-08-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_message_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'subscription', 'verbose_name_plural': 'news subscription'},
        ),
        migrations.AlterModelOptions(
            name='reporting',
            options={'ordering': ['-data'], 'verbose_name': 'reporting', 'verbose_name_plural': 'reportings'},
        ),
        migrations.AlterField(
            model_name='message',
            name='DZO',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='PAO',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='added_via_portal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='comment_delete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='data_moderation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='moderator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='moderator_is_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='report',
            field=models.CharField(choices=[('Прибыли и убытки РТК', 'Прибыли и убытки РТК'), ('РТК + Tele2', 'РТК + Tele2'), ('Сегментная отчетность', 'Сегментная отчетность')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='user',
            field=models.CharField(max_length=100, verbose_name='User mail'),
        ),
    ]
