# Generated by Django 4.2 on 2023-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100)),
                ('external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_via_portal', models.BooleanField(default=True, verbose_name='Добавлено через портал')),
                ('moderator_is_decision', models.BooleanField(default=False, verbose_name='Проверка модератора')),
                ('moderator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модератор')),
                ('data_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('comment_delete', models.TextField(blank=True, null=True, verbose_name='Комментарий при удалении')),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
