# Generated by Django 4.2 on 2023-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('external', models.BooleanField(default=False, verbose_name='Внешний пользователь')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Разрешения')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
