# Generated by Django 4.2.1 on 2023-08-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='external',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='external_user',
            field=models.BooleanField(default=False, verbose_name='External_user'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='news_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date_of_creation'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full_name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Last_active'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissions'),
        ),
    ]
