# Generated by Django 4.2 on 2023-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usermodel_external_alter_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
